language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.05 PINS="bin_prot.113.33.00+4.05:https://github.com/talex5/bin_prot.git#113.33.00+4.05 irmin-git.1.0.0:https://github.com/talex5/irmin.git#1.0.0-cuekeeper"
