language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.04 PINS="bin_prot.114.06+90:https://github.com/talex5/bin_prot.git#cuekeeper mirage-conduit:3.0.1"
